### ISSUE TITLE
Audio engine

### ISSUE THREAD

**Issue by teschnei** [teschnei/lotus-engine#17]
Figure out an audio engine to integrate with (I don't want to write my own, I don't know enough about audio processing) and start examining the sep format to use it.  Spell generators can already start using sounds, as well as some environment ones like the cicadas in Reisenjima. Maybe start footsteps too

**Comment by Cloudef** [comment]
OpenAL-soft perhaps?

**Comment by takhlaq** [comment]
something to keep in mind is footstep sound effects which may be texture rather than mesh
