### ISSUE TITLE
Translate FFXI IDs to DAT path

### ISSUE THREAD

**Issue by teschnei** [teschnei/lotus-engine#9]
Currently loading DATs using a path from the install directory.  It should just take an ID, that is used to index the VTABLEs and FTABLEs, in order to get the correct path.  The translation from ID to VTABLE index is not known to me at the moment except for zones of IDs less than 256, which is an offset of 100 to the zone id.

**Comment by Cloudef** [comment]
https://git.cloudef.pw/filespec.git/tree/src/bin/xi/xi2path.h#n8 is this what you are looking for?

**Comment by teschnei** [comment]
This is the translation from FTABLE entry to ROM path, which I did already have, but it is nice to see you're lurking :)

I was looking for where the id (zone id, or model id, etc) is translated into the index for the VTABLEs.  Deviltti mentioned that to get the VTABLE index for zoneids under 256, you just add 100 to the zoneid, and then scan the VTABLEs for the one with an entry for that new id, and then check the associated FTABLE's index (from the VTABLE entry), which you then use as input to the function you provided here to get the final path.  At least, that is how I understand it from Deviltti's explanation

**Comment by Cloudef** [comment]
The windower project may be a good resource for that 🤔

**Comment by teschnei** [comment]
That's where I got the FTABLE to ROM path from :^)

**Comment by Cloudef** [comment]
It's probably where I originally got it from too. Unfortunately I wasn't for help.
